name: Wheel

on:
  push:
    paths:
      - 'src/**'
      - 'src-python/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'conanfile.txt'
      - '.github/workflows/wheel.yml'
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{github.workspace}}

    steps:

      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan
        run: conan profile detect --force

      - name: Install C++ dependencies
        run: >
          conan install
          --build=missing
          --settings build_type=Release
          --settings compiler.cppstd=17
          ${{github.workspace}}

      - name: Install Python dependencies
        run: >
          python -m pip install
          -r ${{github.workspace}}/requirements.txt

      - name: Build and install package
        run: >
          python -m pip install
          ${{github.workspace}}
          --no-build-isolation

      - name: Test package
        run: python -m pytest

      - name: Build wheel
        run: >
          python -m pip wheel
          ${{github.workspace}}
          --no-build-isolation
          --wheel-dir ${{github.workspace}}/dist
